### PR TITLE
Use fx loader

### PR DESCRIPTION
**Pull request by tomsontom**
* Remove custom packaged OpenJFX
* Use Repackaged OpenJFX-Modules from BestSolution who are installed as JPMS-Modules by the OSGi-Hook provided by efxclipse
* Fix tycho build

To fix compile errors in your IDE please follow - https://tomsondev.bestsolution.at/2020/01/28/setting-up-efxclipse-rcp-development-for-java11-and-pde/

### CODE REVIEW

**Comment by kjkeefe** [comment]
I pulled the use-fx-loader branch (a910be3) and built it with "mvn clean verify." It builds successfully. When I decompressed the macosx zip file and tried to run the app, it throws an error and points to a log file with this in it:

<pre>!SESSION 2021-04-14 14:24:49.243 -----------------------------------------------

eclipse.buildId=unknown
java.version=11.0.8
java.vendor=AdoptOpenJDK
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -keyring /Users/kjkeefe/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/kjkeefe/.eclipse_keyring

!ENTRY org.eclipse.osgi 4 0 2021-04-14 14:24:50.003
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:81)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
</pre>

**Comment by tomsontom** [comment]
Hm can you run with "-console -consoleLog" and inspect osgi state and what does not resolve?

**Comment by kjkeefe** [comment]
<pre>id	State       Bundle
0	ACTIVE      org.eclipse.osgi_3.16.200.v20210226-1447
	            Fragments=1
1	RESOLVED    org.eclipse.fx.osgi_3.7.0.202010120720
	            Master=0
2	RESOLVED    com.google.guava_30.1.0.v20210127-2300
3	RESOLVED    com.google.inject_3.0.0.v201605172100
	            Fragments=4, 5
4	RESOLVED    com.google.inject.assistedinject_3.0.0.v201402270930
	            Master=3
5	RESOLVED    com.google.inject.multibindings_3.0.0.v201605172100
	            Master=3
6	STARTING    com.ibm.icu_67.1.0.v20200706-1749
7	STARTING    com.sun.jna_4.5.1.v20190425-1842
8	RESOLVED    com.sun.jna.platform_4.5.1.v20190425-1842
9	STARTING    io.kaje.eclipse.gef.mvc.examples.shapes_1.0.0.202104141923
10	RESOLVED    javax.annotation_1.3.5.v20200909-1856
11	RESOLVED    javax.inject_1.0.0.v20091030
12	RESOLVED    openjfx.base_11.0.0
13	RESOLVED    openjfx.controls_11.0.0
14	RESOLVED    openjfx.fxml_11.0.0
15	RESOLVED    openjfx.graphics.mac_11.0.0
16	RESOLVED    openjfx.media.mac_11.0.0
17	RESOLVED    openjfx.swing_11.0.0
18	RESOLVED    openjfx.swt_11.0.0
19	RESOLVED    openjfx.web.mac_11.0.0
20	RESOLVED    org.apache.batik.constants_1.13.0.v20200622-2037
21	RESOLVED    org.apache.batik.css_1.13.0.v20200622-2037
22	RESOLVED    org.apache.batik.i18n_1.13.0.v20200622-2037
23	RESOLVED    org.apache.batik.util_1.13.0.v20200622-2037
24	RESOLVED    org.apache.commons.io_2.6.0.v20190123-2029
25	RESOLVED    org.apache.commons.jxpath_1.3.0.v200911051830
26	RESOLVED    org.apache.commons.logging_1.2.0.v20180409-1502
27	ACTIVE      org.apache.felix.gogo.command_1.1.2.v20210111-1007
28	ACTIVE      org.apache.felix.gogo.runtime_1.1.4.v20210111-1007
29	ACTIVE      org.apache.felix.gogo.shell_1.1.4.v20210111-1007
30	RESOLVED    org.apache.felix.scr_2.1.24.v20200924-1939
31	RESOLVED    org.apache.xmlgraphics_2.4.0.v20200622-2037
32	RESOLVED    org.eclipse.core.commands_3.9.800.v20201021-1339
33	STARTING    org.eclipse.core.contenttype_3.7.900.v20210111-0918
34	STARTING    org.eclipse.core.databinding_1.10.100.v20200926-1123
35	RESOLVED    org.eclipse.core.databinding.beans_1.7.200.v20210111-0759
36	RESOLVED    org.eclipse.core.databinding.observable_1.10.0.v20200730-0848
37	STARTING    org.eclipse.core.databinding.property_1.8.100.v20200619-0651
38	STARTING    org.eclipse.core.expressions_3.7.100.v20210203-1000
39	STARTING    org.eclipse.core.jobs_3.10.1100.v20210111-0815
40	STARTING    org.eclipse.core.runtime_3.20.100.v20210111-0815
41	RESOLVED    org.eclipse.e4.core.commands_0.13.0.v20201119-1132
42	STARTING    org.eclipse.e4.core.contexts_1.8.400.v20191217-1710
43	STARTING    org.eclipse.e4.core.di_1.7.700.v20210128-2123
44	RESOLVED    org.eclipse.e4.core.di.annotations_1.6.600.v20191216-2352
45	STARTING    org.eclipse.e4.core.di.extensions_0.16.0.v20200507-0938
46	STARTING    org.eclipse.e4.core.di.extensions.supplier_0.15.800.v20210110-1654
47	STARTING    org.eclipse.e4.core.services_2.2.600.v20210110-1654
48	RESOLVED    org.eclipse.e4.emf.xpath_0.2.800.v20200609-0849
49	STARTING    org.eclipse.e4.ui.bindings_0.13.0.v20201119-1132
50	RESOLVED    org.eclipse.e4.ui.css.core_0.13.0.v20201015-0653
51	STARTING    org.eclipse.e4.ui.css.swt_0.14.100.v20201217-1340
52	STARTING    org.eclipse.e4.ui.css.swt.theme_0.13.0.v20201026-1147
53	STARTING    org.eclipse.e4.ui.di_1.3.0.v20210222-1018
54	RESOLVED    org.eclipse.e4.ui.dialogs_1.2.100.v20201109-2317
55	STARTING    org.eclipse.e4.ui.model.workbench_2.1.1000.v20210111-0958
56	STARTING    org.eclipse.e4.ui.services_1.5.0.v20210115-1333
57	RESOLVED    org.eclipse.e4.ui.widgets_1.2.800.v20201021-1339
58	STARTING    org.eclipse.e4.ui.workbench_1.12.100.v20210122-1731
59	STARTING    org.eclipse.e4.ui.workbench.addons.swt_1.4.100.v20201221-2332
60	STARTING    org.eclipse.e4.ui.workbench.renderers.swt_0.15.0.v20201125-0918
	            Fragments=61
61	RESOLVED    org.eclipse.e4.ui.workbench.renderers.swt.cocoa_0.12.600.v20200416-0656
	            Master=60
62	STARTING    org.eclipse.e4.ui.workbench.swt_0.16.0.v20201230-1610
63	RESOLVED    org.eclipse.e4.ui.workbench3_0.15.500.v20201021-1339
64	STARTING    org.eclipse.emf.common_2.22.0.v20210114-1734
65	STARTING    org.eclipse.emf.ecore_2.23.0.v20200630-0516
66	STARTING    org.eclipse.emf.ecore.change_2.14.0.v20190528-0725
67	STARTING    org.eclipse.emf.ecore.xmi_2.16.0.v20190528-0725
68	STARTING    org.eclipse.equinox.app_1.5.100.v20210212-1143
69	STARTING    org.eclipse.equinox.bidi_1.3.100.v20210212-1143
70	STARTING    org.eclipse.equinox.common_3.14.100.v20210212-1143
71	ACTIVE      org.eclipse.equinox.console_1.4.300.v20210211-2058
72	STARTING    org.eclipse.equinox.event_1.6.0.v20210212-1143
73	RESOLVED    org.eclipse.equinox.launcher_1.6.100.v20201223-0822
	            Fragments=74
74	RESOLVED    org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.2.100.v20210209-1541
	            Master=73
75	STARTING    org.eclipse.equinox.preferences_3.8.200.v20210212-1143
76	STARTING    org.eclipse.equinox.registry_3.10.100.v20210212-1143
77	STARTING    org.eclipse.equinox.simpleconfigurator_1.3.600.v20200721-1308
78	RESOLVED    org.eclipse.gef.common_5.0.1.202103090301
79	STARTING    org.eclipse.gef.fx_5.0.5.202103090301
80	RESOLVED    org.eclipse.gef.fx.jface_5.0.2.202103090301
81	RESOLVED    org.eclipse.gef.fx.swt_5.0.2.202103090301
82	RESOLVED    org.eclipse.gef.geometry_5.0.1.202103090301
83	RESOLVED    org.eclipse.gef.geometry.convert.fx_5.0.0.202103090301
84	STARTING    org.eclipse.gef.mvc.fx_5.2.3.202103090301
85	STARTING    org.eclipse.gef.mvc.fx.ui_5.1.1.202103090301
86	STARTING    org.eclipse.help_3.8.800.v20200525-0755
87	RESOLVED    org.eclipse.jface_3.22.100.v20210126-0831
88	RESOLVED    org.eclipse.jface.databinding_1.12.200.v20210111-0911
89	RESOLVED    org.eclipse.jface.notifications_0.3.0.v20210218-1820
90	RESOLVED    org.eclipse.osgi.services_3.10.0.v20210212-1137
91	RESOLVED    org.eclipse.osgi.util_3.6.0.v20210212-1137
92	RESOLVED    org.eclipse.swt_3.116.0.v20210302-1107
	            Fragments=93, 94
93	RESOLVED    org.eclipse.swt.browser.chromium.cocoa.macosx.x86_64_3.116.0.v20210302-1107
	            Master=92
94	RESOLVED    org.eclipse.swt.cocoa.macosx.x86_64_3.116.0.v20210302-1107
	            Master=92
95	STARTING    org.eclipse.ui_3.119.0.v20210111-1350
96	RESOLVED    org.eclipse.ui.views_3.11.0.v20210111-1351
97	STARTING    org.eclipse.ui.workbench_3.122.100.v20210215-1525
98	RESOLVED    org.eclipse.urischeme_1.1.300.v20210113-1544
99	RESOLVED    org.w3c.css.sac_1.3.1.v200903091627
100	RESOLVED    org.w3c.dom.events_3.0.0.draft20060413_v201105210656
101	RESOLVED    org.w3c.dom.smil_1.0.1.v200903091627
102	RESOLVED    org.w3c.dom.svg_1.1.0.v201011041433</pre>

**Comment by tomsontom** [comment]
Hm - i only launched from eclipse - i'll try to reproduce it

**Comment by kjkeefe** [comment]
Thank you. I'm spinning up a Ubuntu VM to see if it does it there, too.

**Comment by kjkeefe** [comment]
It appears to be the same on Ubuntu 20.04:

<pre>!SESSION 2021-04-14 14:30:41.894 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.10
java.vendor=Ubuntu
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.osgi 4 0 2021-04-14 14:30:42.602
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:81)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1434)</pre>

**Comment by tomsontom** [comment]
so the problem has been the product-File what I find a bit strange is that your list does not contain `org.eclipse.osgi.compatibility.state` which i have when running in eclipse and when exported

**Pull request merged**
